In [1]:
# importing the pandas module
import pandas as pd

# reading the dataset
data = pd.read_csv("Stock_price.csv")


# data head
data.head()

Index        Date         Open         High          Low        Close  \
0   HSI  1986-12-31  2568.300049  2568.300049  2568.300049  2568.300049   
1   HSI  1987-01-02  2540.100098  2540.100098  2540.100098  2540.100098   
2   HSI  1987-01-05  2552.399902  2552.399902  2552.399902  2552.399902   
3   HSI  1987-01-06  2583.899902  2583.899902  2583.899902  2583.899902   
4   HSI  1987-01-07  2607.100098  2607.100098  2607.100098  2607.100098   

     Adj Close  Volume    CloseUSD  
0  2568.300049     0.0  333.879006  
1  2540.100098     0.0  330.213013  
2  2552.399902     0.0  331.811987  
3  2583.899902     0.0  335.906987  
4  2607.100098     0.0  338.923013

In [2]:

# splitting dataframe in a particular size
data = data.sample(frac=0.1,random_state=200)

In [2]:
# dropping the column
data.drop("Index",axis=1, inplace=True)
data.drop("Date",axis=1, inplace=True)

In [3]:
# splitting the dataset into input and output values
x = data[["Open", "High", "High", "High", "Adj Close", "Volume"]]
y = data["CloseUSD"]

# converting to numpy array
x = x.to_numpy()
y = y.to_numpy()

# fixing the shape of output
y = y.reshape(-1, 1)

In [8]:
# importing the modules
from keras.models import Sequential
from keras.layers import Dense, LSTM

# initializing the model
model = Sequential()


# building the neural network with 128 nodes and specifing the input shape 
model.add(LSTM(128, return_sequences=True, input_shape= (x.shape[1], 1)))

# adding hidden layers
model.add(LSTM(64, return_sequences=False))

# adding dense layer
model.add(Dense(25))

# adding output layer
model.add(Dense(1))

In [12]:
# compliting the neural network model
model.compile(optimizer='adam', loss='mean_squared_error')

# fiting the model on 10 epochs 
model.fit(x, y, batch_size=1, epochs=2)

Epoch 1/2
104224/104224 [==============================] - 484s 5ms/step - loss: 11763089.0000
Epoch 2/2
104224/104224 [==============================] - 396s 4ms/step - loss: 10925092.0000


In [14]:
# import numpy
import numpy as np

# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

1/1 [==============================] - 1s 1s/step


array([[1679.2015]], dtype=float32)

In [32]:
# importing the module
from sklearn.gaussian_process import GaussianProcessRegressor

# iniliazing the gaussian process regressor
model = GaussianProcessRegressor()

# training the model
model.fit(x, y)

GaussianProcessRegressor()

In [35]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([[0.]])

In [41]:
# importing the module
from sklearn.linear_model import RANSACRegressor

# Initializing the model
model = RANSACRegressor()

# training the model
model.fit(x, y)

RANSACRegressor()

In [42]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([[153.18575136]])

In [6]:
# importing the required module
from catboost import CatBoostRegressor

# initializing the model
model10 = CatBoostRegressor()

# training the model
model10.fit(x, y)

Learning rate set to 0.085314
0:	learn: 3538.7232837	total: 60.8ms	remaining: 1m
1:	learn: 3353.0685763	total: 72.9ms	remaining: 36.4s
2:	learn: 3184.2131581	total: 85.4ms	remaining: 28.4s
3:	learn: 3033.7271834	total: 97.8ms	remaining: 24.4s
4:	learn: 2905.6190452	total: 113ms	remaining: 22.5s
5:	learn: 2788.7557325	total: 129ms	remaining: 21.3s
6:	learn: 2687.7571453	total: 144ms	remaining: 20.4s
7:	learn: 2593.3369465	total: 156ms	remaining: 19.4s
8:	learn: 2515.5169247	total: 168ms	remaining: 18.5s
9:	learn: 2439.6886588	total: 180ms	remaining: 17.8s
10:	learn: 2371.8215924	total: 193ms	remaining: 17.4s
11:	learn: 2318.2721248	total: 206ms	remaining: 17s
12:	learn: 2263.2144992	total: 216ms	remaining: 16.4s
13:	learn: 2219.5449616	total: 225ms	remaining: 15.9s
14:	learn: 2173.7052697	total: 233ms	remaining: 15.3s
15:	learn: 2139.2006182	total: 241ms	remaining: 14.8s
16:	learn: 2106.2275422	total: 249ms	remaining: 14.4s
17:	learn: 2075.1911116	total: 259ms	remaining: 14.1s
18:	learn

160:	learn: 1636.0590424	total: 1.38s	remaining: 7.17s
161:	learn: 1635.9362355	total: 1.38s	remaining: 7.16s
162:	learn: 1635.1207413	total: 1.39s	remaining: 7.16s
163:	learn: 1634.7889672	total: 1.4s	remaining: 7.16s
164:	learn: 1633.8236795	total: 1.41s	remaining: 7.15s
165:	learn: 1633.1526159	total: 1.42s	remaining: 7.15s
166:	learn: 1632.8467411	total: 1.43s	remaining: 7.14s
167:	learn: 1632.6733273	total: 1.44s	remaining: 7.15s
168:	learn: 1632.2261481	total: 1.45s	remaining: 7.13s
169:	learn: 1631.9389596	total: 1.46s	remaining: 7.14s
170:	learn: 1631.3245285	total: 1.47s	remaining: 7.14s
171:	learn: 1631.1291438	total: 1.48s	remaining: 7.13s
172:	learn: 1630.3416326	total: 1.49s	remaining: 7.13s
173:	learn: 1630.1877983	total: 1.5s	remaining: 7.12s
174:	learn: 1628.9603147	total: 1.51s	remaining: 7.12s
175:	learn: 1628.2735319	total: 1.52s	remaining: 7.12s
176:	learn: 1628.0630062	total: 1.53s	remaining: 7.1s
177:	learn: 1627.5972531	total: 1.54s	remaining: 7.1s
178:	learn: 16

342:	learn: 1579.3473029	total: 2.73s	remaining: 5.23s
343:	learn: 1579.1345937	total: 2.74s	remaining: 5.23s
344:	learn: 1578.9726882	total: 2.75s	remaining: 5.23s
345:	learn: 1578.3845287	total: 2.76s	remaining: 5.22s
346:	learn: 1578.2045680	total: 2.77s	remaining: 5.22s
347:	learn: 1577.7019165	total: 2.79s	remaining: 5.23s
348:	learn: 1577.6233050	total: 2.8s	remaining: 5.23s
349:	learn: 1577.4509949	total: 2.81s	remaining: 5.23s
350:	learn: 1577.2367733	total: 2.83s	remaining: 5.23s
351:	learn: 1576.7943846	total: 2.83s	remaining: 5.22s
352:	learn: 1576.5394566	total: 2.85s	remaining: 5.21s
353:	learn: 1576.4284196	total: 2.86s	remaining: 5.21s
354:	learn: 1576.3487586	total: 2.87s	remaining: 5.21s
355:	learn: 1576.2342709	total: 2.88s	remaining: 5.21s
356:	learn: 1576.1447180	total: 2.89s	remaining: 5.2s
357:	learn: 1575.9801642	total: 2.9s	remaining: 5.2s
358:	learn: 1575.5421781	total: 2.91s	remaining: 5.19s
359:	learn: 1575.4607895	total: 2.92s	remaining: 5.18s
360:	learn: 15

526:	learn: 1551.5582428	total: 3.93s	remaining: 3.53s
527:	learn: 1551.5277733	total: 3.94s	remaining: 3.52s
528:	learn: 1551.4465682	total: 3.95s	remaining: 3.51s
529:	learn: 1551.3984571	total: 3.95s	remaining: 3.5s
530:	learn: 1551.3436503	total: 3.96s	remaining: 3.5s
531:	learn: 1551.2250134	total: 3.96s	remaining: 3.49s
532:	learn: 1551.1865672	total: 3.97s	remaining: 3.48s
533:	learn: 1551.1348937	total: 3.98s	remaining: 3.47s
534:	learn: 1551.0778215	total: 3.98s	remaining: 3.46s
535:	learn: 1551.0184153	total: 3.99s	remaining: 3.46s
536:	learn: 1550.8134784	total: 4s	remaining: 3.45s
537:	learn: 1550.7868218	total: 4s	remaining: 3.44s
538:	learn: 1550.5999459	total: 4.01s	remaining: 3.43s
539:	learn: 1550.4201628	total: 4.01s	remaining: 3.42s
540:	learn: 1550.4032366	total: 4.02s	remaining: 3.41s
541:	learn: 1550.0640462	total: 4.03s	remaining: 3.4s
542:	learn: 1549.9840058	total: 4.03s	remaining: 3.39s
543:	learn: 1549.8633646	total: 4.04s	remaining: 3.38s
544:	learn: 1549.84

676:	learn: 1534.4978370	total: 5.21s	remaining: 2.48s
677:	learn: 1534.4450685	total: 5.21s	remaining: 2.48s
678:	learn: 1534.4284912	total: 5.22s	remaining: 2.47s
679:	learn: 1534.3739809	total: 5.23s	remaining: 2.46s
680:	learn: 1534.2300168	total: 5.24s	remaining: 2.45s
681:	learn: 1533.9906289	total: 5.25s	remaining: 2.45s
682:	learn: 1533.9501440	total: 5.25s	remaining: 2.44s
683:	learn: 1533.7934084	total: 5.26s	remaining: 2.43s
684:	learn: 1533.6823519	total: 5.27s	remaining: 2.42s
685:	learn: 1533.5940834	total: 5.28s	remaining: 2.42s
686:	learn: 1533.4017965	total: 5.28s	remaining: 2.41s
687:	learn: 1533.1320947	total: 5.29s	remaining: 2.4s
688:	learn: 1533.0665603	total: 5.3s	remaining: 2.39s
689:	learn: 1532.9840484	total: 5.3s	remaining: 2.38s
690:	learn: 1532.9725301	total: 5.31s	remaining: 2.37s
691:	learn: 1532.9057889	total: 5.31s	remaining: 2.37s
692:	learn: 1532.8539299	total: 5.32s	remaining: 2.36s
693:	learn: 1532.7042358	total: 5.33s	remaining: 2.35s
694:	learn: 1

829:	learn: 1518.1946356	total: 6.21s	remaining: 1.27s
830:	learn: 1518.0778889	total: 6.21s	remaining: 1.26s
831:	learn: 1517.9680719	total: 6.22s	remaining: 1.26s
832:	learn: 1517.8469621	total: 6.23s	remaining: 1.25s
833:	learn: 1517.7166983	total: 6.24s	remaining: 1.24s
834:	learn: 1517.6340306	total: 6.24s	remaining: 1.23s
835:	learn: 1517.5460131	total: 6.25s	remaining: 1.23s
836:	learn: 1517.4819101	total: 6.25s	remaining: 1.22s
837:	learn: 1517.3514266	total: 6.26s	remaining: 1.21s
838:	learn: 1517.3250147	total: 6.27s	remaining: 1.2s
839:	learn: 1517.2425135	total: 6.27s	remaining: 1.19s
840:	learn: 1517.1727355	total: 6.28s	remaining: 1.19s
841:	learn: 1516.8470046	total: 6.28s	remaining: 1.18s
842:	learn: 1516.8123989	total: 6.29s	remaining: 1.17s
843:	learn: 1516.7590511	total: 6.29s	remaining: 1.16s
844:	learn: 1516.6895822	total: 6.3s	remaining: 1.16s
845:	learn: 1516.5373777	total: 6.3s	remaining: 1.15s
846:	learn: 1516.5016817	total: 6.31s	remaining: 1.14s
847:	learn: 1

996:	learn: 1502.6516347	total: 7.2s	remaining: 21.7ms
997:	learn: 1502.5539636	total: 7.21s	remaining: 14.4ms
998:	learn: 1502.4989320	total: 7.22s	remaining: 7.22ms
999:	learn: 1502.3166284	total: 7.22s	remaining: 0us


In [8]:
import numpy as np

# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model10.predict(features)

array([1993.14150827])

In [5]:
# import lightgbm
import lightgbm as lgb

# initialzing the model
model = lgb.LGBMRegressor()

# train the model
model.fit(x,y)

/home/uca/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LGBMRegressor()

In [6]:
import numpy as np

# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([1939.51101008])

In [8]:
# importing the module
from sklearn.ensemble import ExtraTreesRegressor

# initializing the model
model = ExtraTreesRegressor()

# Training the model
model.fit(x, y)

/tmp/ipykernel_28526/1002318426.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x, y)


ExtraTreesRegressor()

In [9]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([1768.06574021])

In [11]:
# importing the xgboost model
import xgboost as xgb

# xgboost regressor
model = xgb.XGBRegressor()

# training the model
model.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [12]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([1365.6316], dtype=float32)

In [13]:
# importing the regressor
from sklearn.ensemble import GradientBoostingRegressor

# training the model with 
model=GradientBoostingRegressor()

# training the model
model.fit(x, y)

/home/uca/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor()

In [14]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([1593.15278206])

In [15]:
# importing ada boost regressor
from sklearn.ensemble import AdaBoostRegressor

# Create adaboost regressor
model = AdaBoostRegressor()

# training the ada boost regressor
model.fit(x, y)

/home/uca/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostRegressor()

In [16]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([1445.94457662])

In [17]:
# importing the model
from sklearn.ensemble import RandomForestRegressor

# instantiate random forest method
model = RandomForestRegressor()

# fit the model
model.fit(x, y)

/tmp/ipykernel_28526/296483454.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x, y)


RandomForestRegressor()

In [18]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([1473.78491856])

In [19]:
# importing the decision tree
from sklearn.tree import DecisionTreeRegressor

# initializing the model
model = DecisionTreeRegressor()

# providing the training dataset
model.fit(x,y)

DecisionTreeRegressor()

In [20]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([2584.219971])

In [21]:
# importing the model 
from sklearn.linear_model import LinearRegression

# linear regression 
model = LinearRegression()

# training the model
model.fit(x,y)


LinearRegression()

In [22]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([[2347.01284449]])