In [36]:
# importing the pandas module
import pandas as pd

# reading the dataset
data = pd.read_csv("Stock_price.csv")


# data head
data.head()

Index        Date         Open         High          Low        Close  \
0   HSI  1986-12-31  2568.300049  2568.300049  2568.300049  2568.300049   
1   HSI  1987-01-02  2540.100098  2540.100098  2540.100098  2540.100098   
2   HSI  1987-01-05  2552.399902  2552.399902  2552.399902  2552.399902   
3   HSI  1987-01-06  2583.899902  2583.899902  2583.899902  2583.899902   
4   HSI  1987-01-07  2607.100098  2607.100098  2607.100098  2607.100098   

     Adj Close  Volume    CloseUSD  
0  2568.300049     0.0  333.879006  
1  2540.100098     0.0  330.213013  
2  2552.399902     0.0  331.811987  
3  2583.899902     0.0  335.906987  
4  2607.100098     0.0  338.923013

In [29]:

# splitting dataframe in a particular size
data = data.sample(frac=0.1,random_state=200)

In [37]:
# dropping the column
data.drop("Index",axis=1, inplace=True)
data.drop("Date",axis=1, inplace=True)

In [38]:
# splitting the dataset into input and output values
x = data[["Open", "High", "High", "High", "Adj Close", "Volume"]]
y = data["CloseUSD"]

# converting to numpy array
x = x.to_numpy()
y = y.to_numpy()

# fixing the shape of output
y = y.reshape(-1, 1)

In [8]:
# importing the modules
from keras.models import Sequential
from keras.layers import Dense, LSTM

# initializing the model
model = Sequential()


# building the neural network with 128 nodes and specifing the input shape 
model.add(LSTM(128, return_sequences=True, input_shape= (x.shape[1], 1)))

# adding hidden layers
model.add(LSTM(64, return_sequences=False))

# adding dense layer
model.add(Dense(25))

# adding output layer
model.add(Dense(1))

In [12]:
# compliting the neural network model
model.compile(optimizer='adam', loss='mean_squared_error')

# fiting the model on 10 epochs 
model.fit(x, y, batch_size=1, epochs=2)

Epoch 1/2
104224/104224 [==============================] - 484s 5ms/step - loss: 11763089.0000
Epoch 2/2
104224/104224 [==============================] - 396s 4ms/step - loss: 10925092.0000


In [14]:
# import numpy
import numpy as np

# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

1/1 [==============================] - 1s 1s/step


array([[1679.2015]], dtype=float32)

In [32]:
# importing the module
from sklearn.gaussian_process import GaussianProcessRegressor

# iniliazing the gaussian process regressor
model = GaussianProcessRegressor()

# training the model
model.fit(x, y)

GaussianProcessRegressor()

In [35]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([[0.]])

In [41]:
# importing the module
from sklearn.linear_model import RANSACRegressor

# Initializing the model
model = RANSACRegressor()

# training the model
model.fit(x, y)

RANSACRegressor()

In [42]:
# input values
Open = 2568.300049
High = 2540.100098
low = 2552.399902
close = 2583.899902
ad_price = 2607.100098
volume = 0

# concerting the input to array
features = np.array([[Open, High, low, close, ad_price, volume]])

# prediting the closing price
model.predict(features)

array([[153.18575136]])